### ISSUE TITLE
Can't able to load VAST XML

### ISSUE THREAD

**Issue by pratik24mac** [radiantmediaplayer/rmp-vast#31]
How I can use inline wrapper or directly I can pass XML string as a vast

How i can use VAST XML ?

**Comment by radiantmediaplayer** [comment]
Hi, the parsing of XML happens at _onXmlAvailable but this is an internal method and the player follows the pattern of having to fetch a VAST tag from a URI before starting the XML parsing. I am going to mark this as feature request, we may implement this at a later point in time if time allows, otherwise a PR is welcome.

**Comment by radiantmediaplayer** [comment]
Featured in https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v11.0.0
